assessment
learn-academy-2022-delta/week-5-assessment-Ahmedkhafaji pull request #1
Opened 2022-07-18 17:08 UTC by Ahmedkhafaji

# Submitting Week 5 Assessment

### ✅ Completed Files

Mark the following as confirmation that the files in this repository are complete.

- [ x] JavaScript Coding Challenges
- [x ] Ruby Coding Challenges
- [ x] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:

2022-07-18 17:34 UTC, elysemontano requested changes
Requesting one change: Please provide pseudocode for problem 3 on code challenges.  Once this is added, I will approve this PR.
Other comments: Overall, you did a really great job on this assessment!  Your code is efficient and well written, interview answers were good and Ruby section was spot on.  To level up, try thinking about edge cases in your code and implementing tests and code that account for them.  Keep up the great work!

2022-07-18 17:34 UTC, elysemontano commented on code-challenges.test.js
> +//Test Suites: 1 passed, 1 total
This looks wonderful Ahmed!!  Great work!

2022-07-18 17:34 UTC, elysemontano commented on code-challenges.test.js
> +  }
I really like this approach!  One thing to consider is if the value in the pair is greater than or less than the three of a kind.  Currently, [5, 5, 3, 3, 3] will pass but [5, 5, 5, 4, 4] will fail.

2022-07-18 17:34 UTC, elysemontano commented on interview-questions.md
> +Researched answer:gives a unique ID for each set of data, it is important because it helps to avoid duplicates.
Awesome work on this section!

2022-07-18 17:34 UTC, elysemontano commented on ruby-challenges.rb
> +p my_bike.getInfo
💯

2022-07-18 17:34 UTC, elysemontano commented on code-challenges.test.js
> +const fullHouse = (array) => {
I don't see any pseudocode for this problem.

2022-07-19 16:26 UTC, Ahmedkhafaji commented
I thought I did the pseudo code for number 3! did not see that sorry for the delay Elyse. thank you on the feed back, Noted!

2022-07-19 23:09 UTC, elysemontano approved these changes
Great work Ahmed!

2022-07-19 23:09 UTC, elysemontano commented on code-challenges.test.js
> +const fullHouse = (array) => {
Great!  Thank you for adding that in!

2022-07-19 23:51 UTC, merged